rueng_projects/account/urls.py
from django.urls import path
from account import views as account_view
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

app_name = 'account'

urlpatterns = [
    path('login/', account_view.login_view ,name='login'),
    path('logout/', account_view.logout_view, name='logout'),
    path('signup/', account_view.signup ,name='signup'),
]

rueng_projects/config/urls.py
from django.contrib import admin
from django.urls import path, include
from yesasia import views as yesasia_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', yesasia_views.index,name='rueng_home'),
    path('yesasia/', include('yesasia.urls')),
    path('yandex/', include('yandex_news.urls')),
    path('random_reading/', include('random_reading.urls')),
    path('mywordbook/', include('mywordbook.urls')),
    path('accounts/', include('account.urls')),
]

rueng_projects/templates/article_content.html
{% load static %}
<div class="article-title-wrapper">
    {% for title in article_title_list %}
        <span class="title-text" onclick="word_click_event(this)">{{ title }}</span>
    {% endfor %}
        <button class="dictionary-icon">
            <img src="{% static 'img/ico_book.png' %}" alt="dictionary-icon" onclick="dictionary_icon_event()">
        </button>
</div>
{% for article_body in article_body_list %}
<div class="article-body-wrapper">
    {% for article in article_body%}
        <span class="body-text" onclick="word_click_event(this)">{{article}}</span>
    {% endfor%}
</div>
{% endfor %}
<div class="article-save-wrapper">
    {% if is_read == 0 %}
        <button class="article-save-button" onclick="save_article()">done reading?</button>
        <img class="read-checked" src="{% static 'img/check2-square.png' %}" alt="read-checked-img" style="display: none;">
    {% elif is_read == 1 %}
        <button class="article-save-button" onclick="save_article()">finished reading!</button>
        <img class="read-checked" src="{% static 'img/check2-square.png' %}" alt="read-checked-img" style="display: inline;">
    {% endif %}
</div>

rueng_projects/templates/dictionary.html
{% load static %}
<div class="dictionary-header">
    <img src="{% static 'img/favicon_img.png' %}" alt="rueng-dictionary-img">
    <span class="title-main">Rueng Dictionary</span>
    <span class="title-small">powered by wiktionary</span>
    <img src="{% static 'img/x-circle.png' %}" alt="close-icon" class="close-icon" onclick="dictionary_icon_event()">
</div>
<div class="dictionary-search">
    <input type="text" name="search_word" class="search_box">
    <button id="search-button" onclick="button_click_event()">search</button>
    <button id="save-button" onclick="save_word_event()">save word</button>
    <div class="word-saved-checked" style="display: none;">
        <img class="vocab-checked-img" src="{% static 'img/check2-square.png' %}" alt="word-saved-success-mark">
        <span class="vocab-checked-label">saved!</span>
    </div>
</div>

<div class="dictionary-content"></div>

rueng_projects/templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rueng</title>
    <link rel="stylesheet" href="../../static/css/bootstrap-5.3.2-dist/css/bootstrap.css">
    <link rel="stylesheet" href="../../static/css/index.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Philosopher&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href="../../static/img/favicon_img.png">
</head>
<body>
    <div id ="home" class="big-bg">
        <header class="page-header wrapper">
            <h1><a href="{% url 'rueng_home' %}" class="logo">Rueng</a></h1>
            <nav>
                {% include 'navbar.html' %}
            </nav>
        </header>
        <div class="home-content wrapper">
            <h2 class="page-title">Learn Russian by English!</h2>
            <p>Read various articles in Russian with our fast, accurate Russian dictionary app and boost your Russian skills.</p>
            
            {% if user.is_authenticated %}
            <a href="random_reading/" class="button">Start</a>
            {% endif %}
            {% if not user.is_authenticated %}
            <a href="{% url 'account:login' %}" class="button">Login</a>
            {% endif %}

        </div>
    </div>
</body>
</html>

rueng_projects/templates/list_table.html
{% load static %}

<div class="list-table-wrapper">
    <table class="article-list-table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">title</th>
                <th scope="col">status</th>
                <th scope="col">update date</th>
            </tr>
        </thead>
        <tbody>
            {% for page_obj in page_obj_list%}
                <tr>
                    <td>{{ page_obj_list.start_index|add:forloop.counter0 }}</td>
                    <td class="article-title-link"><a href="{{page_obj.article_id}}" class="article_link">{{page_obj.title}}</a></td>
                    <td>
                        {% if page_obj.is_read == 0 %}
                            <img src="{% static 'img/pencil-fill.png'%}" alt="status img">
                        {% elif page_obj.is_read == 1 %}
                            <img src="{% static 'img/check2-square.png'%}" alt="status img">
                        {% endif %}
                    </td>
                    <td>{{page_obj.update_date}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="paginator-button-wrapper" aria-label="article-list-nav">
    <ul class="pagination">
        {% if page_obj_list.has_previous %}
            <li class="page-item previous-button"><a class="page-link" href="?page={{page_obj_list.previous_page_number}}"><span>Previous</span></a></li>
        {% endif %}
        {% for page in paginator.page_range%}
            {% if page >= page_obj_list.number|add:-4 and page <= page_obj_list.number|add:4 %}
                {% if page == page_obj_list.number %}
                    <li class="page-item active pagination-button-list">
                        <a class="page-link" href="?page={{page}}"><span class="sr-only">{{page}}</span></a>
                    </li>                    
                {% else %}
                    <li class="page-item pagination-button-list">
                        <a class="page-link" href="?page={{page}}"><span>{{page}}</span></a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% if page_obj_list.has_next %}
        <li class="page-item next-button"><a class="page-link" href="?page={{page_obj_list.next_page_number}}"><span>Next</span></a></li>
        {% endif %}
    </ul>
</div>

rueng_projects/templates/navbar.html
{% load static %}

{% if user.is_authenticated %}
<div class="user-info-wrapper">
    <img src="{% static 'img/person.png' %}" alt="user-icon" class="user-icon">
    <span>Welcome {{user.first_name}}!</span>
</div>
{% endif %}
<ul class="main-nav">
    <li><a href="{% url 'yesasia_article_list' 'view-all' %}">Yes Asia</a></li>
    <li><a href="{% url 'yandex_article_list' 'view-all' %}">Yandex News</a></li>
    <li><a href="{% url 'mywordbook_main' %}">My Wordbook</a></li>
    
    {% if user.is_authenticated %}
    <li><a href="{% url 'account:logout' %}">Logout</a></li>
    {% endif %}
</ul>